// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyrSf5Smuzv6-nhJ_A83t2b8v5unqlv3E',
    appId: '1:736815774564:web:282a6476ca02adc8ea9871',
    messagingSenderId: '736815774564',
    projectId: 'gtt-app-ca92a',
    authDomain: 'gtt-app-ca92a.firebaseapp.com',
    storageBucket: 'gtt-app-ca92a.appspot.com',
    measurementId: 'G-1VW0CQ2Q7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6G755XUUXw2hLF3mE6zK-kMs4-FVpaqQ',
    appId: '1:736815774564:android:1975acc2080c3373ea9871',
    messagingSenderId: '736815774564',
    projectId: 'gtt-app-ca92a',
    storageBucket: 'gtt-app-ca92a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlMm_4Mnxbm53Ahrla4lYcJawDb0et5Zc',
    appId: '1:736815774564:ios:a745f90c1c236fe6ea9871',
    messagingSenderId: '736815774564',
    projectId: 'gtt-app-ca92a',
    storageBucket: 'gtt-app-ca92a.appspot.com',
    iosClientId: '736815774564-h21hs2paa2svotm7klplu5jvifktrn0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlMm_4Mnxbm53Ahrla4lYcJawDb0et5Zc',
    appId: '1:736815774564:ios:a745f90c1c236fe6ea9871',
    messagingSenderId: '736815774564',
    projectId: 'gtt-app-ca92a',
    storageBucket: 'gtt-app-ca92a.appspot.com',
    iosClientId: '736815774564-h21hs2paa2svotm7klplu5jvifktrn0b.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtt',
  );
}
